# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: 2334708709@qq.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: "/jekyll-resume"
url: "https://bakasui.gitee.io"
name: Shuyu Chen
job: college student
location: Ningde, China
languages: Ongniel, Wanna One and Choi minho
twitter_username: Minielong
github_username:  bakasui
codepen_username:  nothing
email_address: 2334708709@qq.com

# Build settings
markdown: kramdown
